import DeleteButtonEdge from "../components/DelButtonEdge";
import ModelNode from "../Node/Model";
import DatasetNode from "../Node/Dataset";
import MLOutputNode from "../Node/MLOutput";
import EvalOPNode from "../Node/EvalOP";
import PromptDataset from "../Node/PromptDataset";
import RLConfig from "../Node/RLConfig";
import {
  Layers,
  FileText,
  Database,
  FolderOutput,
  BrainCircuit,
} from "lucide-react";
import type { Node, NodeTypes } from "@xyflow/react";
import type { t_CustomNodeData } from "../components/NodeSidePanel";
const ICON_COLORS = {
  // textOP: "bg-cyan-500/20 text-cyan-400 border border-cyan-500/30",
  // codeBlock: "bg-teal-500/20 text-teal-400 border border-teal-500/30",
  // summary: "bg-pink-500/20 text-pink-400 border border-pink-500/30",
  dataset: "bg-emerald-500/20 text-emerald-400 border border-emerald-500/30",
  basemodel: "bg-blue-500/20 text-blue-400 border border-blue-500/30",
  mloutput: "bg-yellow-500/20 text-yellow-400 border border-yellow-500/30",
  evaluation: "bg-purple-500/20 text-purple-400 border border-purple-500/30",
  promptdataset: "bg-green-500/20 text-green-400 border border-green-500/30",
  rlconfig: "bg-orange-500/20 text-orange-400 border border-orange-500/30",
};
const BASE_COLORS = {
  basemodel: "blue",
  dataset: "emerald",
  mloutput: "amber",
  evaluation: "purple",
  promptdataset: "green",
  rlconfig: "orange",
};
const initialNodes: Node<t_CustomNodeData>[] = [
  {
    id: "1",
    type: "dataset",
    position: { x: 100, y: -50 },
    data: {
      label: "Dataset 1",
      description: "Add a data from the Hugging face dataset link.",
      status: "Ready",
      HFdataset: "HuggingFaceH4/testing_codealpaca_small",
    },
  },
  {
    id: "2",
    type: "dataset",
    position: { x: 100 * 5, y: -50 },
    data: {
      label: "Dataset 2",
      description: "Add a data from the Hugging face dataset link.",
      status: "Ready",
      HFdataset: "timdettmers/openassistant-guanaco",
    },
  },
  {
    id: "3",
    type: "dataset",
    position: { x: 100 * 9, y: -50 },
    data: {
      label: "Dataset 3",
      description: "Add a data from the Hugging face dataset link.",
      status: "Ready",
      HFdataset: "yahma/alpaca-cleaned",
    },
  },
  {
    id: "4",
    type: "basemodel",
    position: { x: 500, y: 300 },
    data: {
      label: "Base Model",
      basemodel: "HuggingFaceTB/SmolLM2-135M-Instruct",
      inputCount: 3,
    },
  },
  {
    id: "5",
    type: "mloutput",
    position: { x: 550, y: 600 },
    data: {
      label: "ML Output",
      description: "The output generated by the machine learning model.",
      inputCount: 3,
      // clusterID: null,
      // modelLink: null,
    },
  },
];

const initialEdges = [
  {
    id: "e1-4a",
    source: "1",
    target: "4",
    animated: false,
    style: { stroke: "#10b981", strokeWidth: 2, strokeDasharray: "5,5" },
    type: "deleteButton",
  },
  {
    id: "e2-4b",
    source: "2",
    target: "4",
    animated: false,
    targetHandle: "input-2",
    style: { stroke: "#10b981", strokeWidth: 2, strokeDasharray: "5,5" },
    type: "deleteButton",
  },
  {
    id: "e3-4c",
    source: "3",
    target: "4",
    targetHandle: "input-3",
    animated: false,
    style: { stroke: "#10b981", strokeWidth: 2, strokeDasharray: "5,5" },
    type: "deleteButton",
  },
  {
    id: "e4-5",
    source: "4",
    target: "5",
    animated: false,
    style: { stroke: "#10b981", strokeWidth: 2, strokeDasharray: "5,5" },
    type: "deleteButton",
  },
];

const nodeTypes: NodeTypes = {
  basemodel: ModelNode,
  dataset: DatasetNode,
  mloutput: MLOutputNode,
  evaluation: EvalOPNode,
  promptdataset: PromptDataset,
  rlconfig: RLConfig,
};

const edgeTypes = {
  deleteButton: DeleteButtonEdge,
};

const nodeOptions = [
  {
    type: "basemodel",
    icon: Layers,
    color: "blue",
    label: "Base model",
    description: "The Base Model over which the Dataset is trained",
  },
  {
    type: "dataset",
    icon: Database,
    color: "emerald",
    label: "Dataset",
    HFdataset: "timdettmers/openassistant-guanaco",
    description: "The dataset used for training the base model",
  },
  {
    type: "mloutput",
    icon: FolderOutput,
    color: "yellow",
    label: "ML Output",
    basemodel: "HuggingFaceTB/SmolLM2-135M-Instruct",
    description: "The output generated by the machine learning model.",
  },
  {
    type: "evaluation",
    icon: FileText,
    color: "purple",
    label: "Evaluation OP",
    description: "Evaluate the performance of the ML model.",
  },
  {
    type: "promptdataset",
    icon: FileText,
    color: "green",
    label: "Prompt Dataset",
    description:
      "Dataset specifically for Renforcement Learning from Human Feedback (RLHF).",
  },
  {
    type: "rlconfig",
    icon: BrainCircuit,
    color: "orange",
    label: "RL",
    description: "Configuration for Reinforcement Learning settings.",
  },
];

const CHILD_NODE_HEIGHT = 170;
const NODE_VERTICAL_SPACING = 50;
const HORIZONTAL_BRANCH_SPACING = 1200;
const CHILD_WIDTH_OFFSET = 400;

export {
  ICON_COLORS,
  BASE_COLORS,
  initialNodes,
  initialEdges,
  nodeTypes,
  edgeTypes,
  nodeOptions,
  CHILD_NODE_HEIGHT,
  NODE_VERTICAL_SPACING,
  HORIZONTAL_BRANCH_SPACING,
  CHILD_WIDTH_OFFSET,
};
